### ISSUE TITLE
Forestry Error

### ISSUE THREAD

**Issue by SerialCrasher23** [nhave/The-One-Wrench#1]
Using the wrench in wrenching and smart wrench modes result in a crash. Disabling forestry support resolve the issue. Posting links to the crash report (pastebin) and the full log (Sendspace)

https://pastebin.com/m83RZNq6
https://www.sendspace.com/file/e3rxsz

**Comment by nhave** [comment]
Fixed in the new release, it should be ready soon on curseforge.
