### ISSUE TITLE
[1.12.2] Crash with IE

### ISSUE THREAD

**Issue by MokahTGS** [nhave/The-One-Wrench#2]
Description of the issue:
Crash

Crashlog:
https://pastebin.com/X9K0gTB0

Versions & Modlist
Forge 2611
IE 12.77
Immersive Petroleum 1.1.7
Immersive Tech 1.3.5
The One Wrench 1.12.2.2.1.1

Rolling back to the previous version stops the crash.

**Comment by nhave** [comment]
I couldnt recreate the crash but it should be fixed now, please let me know if it does. :)
